name: "npm install"
description: "Install npm packages"

inputs:
  should-build:
    description: "Npm build to run"
    default: prod
  cache-was-hit:
    description: "Check if cache was hit"
    default: false

runs:
  using: "composite"
  steps:

    - name: install npm packages
      if: ${{ inputs.cache-was-hit }} != true
      run: npm install --no-save
      shell: bash

    - name: build assets
      run: npm run ${{ inputs.should-build }}
      shell: bash
